backend:
  name: github
  repo: ArtiPedia/blog
  preview_context: my-provider/deployment
  
site_url: https://blog.artipedia.id
  
media_folder: "img/"
public_folder: "/img/"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "news_item"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - {label: "Path", name: "path", widget: "image"}
          - {label: "Feature image path", name: "feature", widget: "image"}
          - {label: "Image width", name: "width", widget: "number", valueType: "int"}
          - {label: "Image height", name: "height", widget: "number", valueType: "int"}
          - {label: "Image caption", name: "caption", widget: "string"}
      - {label: "Last modified date", name: "last_modified_date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
     
