backend:
  name: github
  repo: ArtiPedia/blog
  preview_context: my-provider/deployment

publish_mode: editorial_workflow
  
site_url: https://blog.artipedia.id
  
media_folder: "img/"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "news_item"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Last modified date", name: "last_modified_date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "authors"
    label: "Authors"
    file: "_data/authors.yml"
    description: "Author descriptions"
    fields:
      - name: authors
        label: Authors
        label_singular: "Author"
        widget: list
        fields:
          - { label: "Nickname", name: "nickname", widget: "string", hint: "Nickname" }
          - { label: "Name", name: "name", widget: "string", hint: "First and Last" }
          - { label: "Slug", name: "slug", widget: "string", hint: "example firs-lastname" }
          - { label: "Avatar", name: "avatar", widget: "image", hint: "First and Last" }
          - { label: "Bio", name: "bio", widget: "string", hint: "Bio Description" }
          - { label: "Email", name: "email", widget: "string", hint: "contoh@gmail.com" }
          - { label: "Twitter", name: "twitter", widget: "string", hint: "contoh artipedia" }
          - { label: "Facebook", name: "facebook", widget: "string", hint: "contoh artipedia" }
